import RamseySpace.Baire

/-!
# The Ellentuck topology

Basic neighborhoods [a,B] form the basis.  We define the topology by its local
basis condition, which avoids any auxiliary coding choices.
-/

namespace RamseySpace

universe u v

namespace ApproximationSystem

variable (S : ApproximationSystem.{u, v})

/-- Local basis characterization of Ellentuck-open sets. -/
def IsEllentuckOpen (U : Set S.Point) : Prop :=
  ∀ ⦃X : S.Point⦄, X ∈ U →
    ∃ (n : ℕ) (a : S.Approx n) (B : S.Point),
      X ∈ S.neighborhood a B ∧ S.neighborhood a B ⊆ U

/-- The Ellentuck topology generated by the basic neighborhoods [a,B]. -/
def ellentuckTopology : TopologicalSpace S.Point where
  IsOpen := S.IsEllentuckOpen
  isOpen_univ := by
    intro X hX
    refine ⟨0, S.empty, X, ?_, Set.subset_univ _⟩
    exact ⟨S.le_refl X, S.approx_zero X⟩
  isOpen_inter := by
    intro U V hU hV X hX
    rcases hU hX.1 with ⟨n, a, B, hXB, hBU⟩
    rcases hV hX.2 with ⟨m, b, C, hXC, hCV⟩
    let l := max n m
    let c : S.Approx l := S.approx l X
    have hac : S.IsInitial a c := by
      refine ⟨Nat.le_max_left n m, X, hXB.2, rfl⟩
    have hbc : S.IsInitial b c := by
      refine ⟨Nat.le_max_right n m, X, hXC.2, rfl⟩
    refine ⟨l, c, X, ⟨S.le_refl X, rfl⟩, ?_⟩
    intro Z hZ
    constructor
    · apply hBU
      apply S.neighborhood_mono hXB.1
      exact S.neighborhood_initial_subset hac hZ
    · apply hCV
      apply S.neighborhood_mono hXC.1
      exact S.neighborhood_initial_subset hbc hZ
  isOpen_sUnion := by
    intro T hT X hX
    rcases Set.mem_sUnion.mp hX with ⟨U, hUT, hXU⟩
    rcases hT U hUT hXU with ⟨n, a, B, hXB, hsub⟩
    exact ⟨n, a, B, hXB, hsub.trans (Set.subset_sUnion_of_mem hUT)⟩

@[simp] theorem isOpen_ellentuck_iff (U : Set S.Point) :
    @IsOpen S.Point S.ellentuckTopology U ↔ S.IsEllentuckOpen U :=
  Iff.rfl

theorem isOpen_neighborhood {n : ℕ} (a : S.Approx n) (B : S.Point) :
    @IsOpen S.Point S.ellentuckTopology (S.neighborhood a B) := by
  change S.IsEllentuckOpen (S.neighborhood a B)
  intro X hX
  exact ⟨n, a, B, hX, fun _ h => h⟩

/-- An Ellentuck-open set is abstract Baire. -/
theorem IsEllentuckOpen.isAbstractBaire {U : Set S.Point}
    (hU : S.IsEllentuckOpen U) :
    IsAbstractBaire U := by
  intro n a Y hne
  by_cases hmeet :
      ∃ X, X ∈ S.neighborhood a Y ∧ X ∈ U
  · rcases hmeet with ⟨X, hXaY, hXU⟩
    rcases hU hXU with ⟨m, c, B, hXcB, hcBU⟩
    let l := max n m
    let b : S.Approx l := S.approx l X
    have hab : S.IsInitial a b :=
      ⟨Nat.le_max_left n m, X, hXaY.2, rfl⟩
    have hcb : S.IsInitial c b :=
      ⟨Nat.le_max_right n m, X, hXcB.2, rfl⟩
    have hsubU : S.neighborhood b X ⊆ U := by
      intro Z hZ
      apply hcBU
      apply S.neighborhood_mono hXcB.1
      exact S.neighborhood_initial_subset hcb hZ
    refine ⟨l, b, X, hab, hXaY.1, ?_, Or.inl hsubU⟩
    exact ⟨X, S.le_refl X, rfl⟩
  · refine ⟨n, a, Y, S.isInitial_refl a, S.le_refl Y, hne, Or.inr ?_⟩
    rw [Set.disjoint_left]
    intro X hXaY hXU
    exact hmeet ⟨X, hXaY, hXU⟩

end ApproximationSystem

/-- Ellentuck-open sets are Ramsey once fusion is available. -/
theorem isRamsey_of_isEllentuckOpen
    {S : ApproximationSystem.{u, v}} (R : AbstractRamseySpace S)
    (C : FusionComplete S) {U : Set S.Point}
    (hU : S.IsEllentuckOpen U) :
    IsRamsey R U :=
  (ApproximationSystem.IsEllentuckOpen.isAbstractBaire hU).isRamsey R C

end RamseySpace
